In [ ]:
#importing libraries

import numpy as np
import pandas as pd

#####**Task - 1:** Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [ ]:
f1 = np.random.randint(100, size=4)
f1

array([29, 62, 14, 33])

In [ ]:
f2 = np.around(np.random.rand(4), 2)
f2

array([0.82, 0.35, 0.71, 0.82])

In [ ]:
f3 = np.around(np.random.rand(4)*10, 2)
f3

array([5.32, 9.47, 2.29, 3.45])

In [ ]:
f4 = np.random.randint(100, size = 4)
f4

array([ 1, 32, 50, 23])

In [ ]:
df = pd.DataFrame(data = [f1,f2,f3,f4])
df

       0      1      2      3
0  29.00  62.00  14.00  33.00
1   0.82   0.35   0.71   0.82
2   5.32   9.47   2.29   3.45
3   1.00  32.00  50.00  23.00

#####**Task - 2:** Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
columns = ['Random Value 1', 'Random Value 2', 'Random Value 3', 'Random Value 4']
df.columns = columns
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0           29.00           62.00           14.00           33.00
1            0.82            0.35            0.71            0.82
2            5.32            9.47            2.29            3.45
3            1.00           32.00           50.00           23.00

#####**Task - 3:** Find the descriptive statistics of the 'df' dataframe.

In [ ]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000         4.00000
mean         9.035000       25.955000       16.750000        15.06750
std         13.471574       27.466072       22.945575        15.51834
min          0.820000        0.350000        0.710000         0.82000
25%          0.955000        7.190000        1.895000         2.79250
50%          3.160000       20.735000        8.145000        13.22500
75%         11.240000       39.500000       23.000000        25.50000
max         29.000000       62.000000       50.000000        33.00000

#####**Task - 4:** Check for the null values in 'df' and find the data type of the columns.

In [ ]:
df.isnull().sum()

Random Value 1    0
Random Value 2    0
Random Value 3    0
Random Value 4    0
dtype: int64

In [ ]:
df.dtypes

Random Value 1    float64
Random Value 2    float64
Random Value 3    float64
Random Value 4    float64
dtype: object

#####**Task - 5:** Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [ ]:
df.loc[:, 'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0           62.00           14.00
1            0.35            0.71
2            9.47            2.29
3           32.00           50.00

In [ ]:
df.iloc[:,1:3]

   Random Value 2  Random Value 3
0           62.00           14.00
1            0.35            0.71
2            9.47            2.29
3           32.00           50.00